### ISSUE TITLE
plot does not render

### ISSUE THREAD

**Issue by bwanaaa** [Overv/ColorScatterPlot#2]
I downloaded code and opened index.html
The page renders all the static elements but plot is blank.
The live web page loads and functions fine on my machine.
The code of the page source and that from github are identical.
I am running MacOS, Safari

What am I missing?

**Comment by Overv** [comment]
The problem is most likely a security issue with the `file:///` protocol. Try serving the webpage on `localhost` instead of opening `index.html` directly.
